import { useCallback, useEffect, useState } from 'react';
import { Download, History, LoaderCircle, LogOut, RefreshCw } from 'lucide-react';
import { getHistoryDownloadUrl, getTranscriptHistory, type TranscriptHistoryItem } from '../services/historyService';
import { signOut } from '../services/authService';

export default function TranscriptHistoryPanel() {
  const [items, setItems] = useState<TranscriptHistoryItem[]>([]);
  const [status, setStatus] = useState<'idle' | 'loading' | 'error'>('idle');
  const load = useCallback(async () => { setStatus('loading'); try { setItems(await getTranscriptHistory()); setStatus('idle'); } catch { setStatus('error'); } }, []);
  useEffect(() => { void load(); }, [load]);
  const download = useCallback(async (historyId: string) => { try { const url = await getHistoryDownloadUrl(historyId); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'livecap-transcript.txt'; anchor.rel = 'noopener noreferrer'; document.body.appendChild(anchor); anchor.click(); anchor.remove(); } catch { setStatus('error'); } }, []);
  return <aside className="border-t border-[#dce5f2] px-6 py-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><History className="h-4 w-4 text-emerald-pro" /><p className="text-sm font-bold text-ink">Transcript history</p></div><button type="button" onClick={() => void load()} aria-label="Refresh transcript history" className="text-ink-muted hover:text-emerald-pro"><RefreshCw className={`h-3.5 w-3.5 ${status === 'loading' ? 'animate-spin' : ''}`} /></button></div><div className="mt-4 space-y-2">{status === 'loading' && <div className="flex items-center gap-2 text-xs text-ink-muted"><LoaderCircle className="h-3 w-3 animate-spin" /> Loading history</div>}{status === 'error' && <p className="text-xs text-crimson">History could not be loaded. Sign in again and retry.</p>}{status === 'idle' && items.length === 0 && <p className="text-xs leading-relaxed text-ink-muted">Exported transcripts will appear here for 14 days.</p>}{items.map((item) => <div key={item.history_id} className="flex items-center justify-between gap-2 rounded-lg border border-[#dce5f2] p-3"><div className="min-w-0"><p className="text-xs font-semibold text-ink">{new Date(item.created_at).toLocaleString()}</p><p className="mt-0.5 text-[11px] text-ink-muted">{item.segment_count} captions</p></div><button type="button" onClick={() => void download(item.history_id)} className="shrink-0 text-emerald-pro hover:opacity-70" aria-label="Download transcript"><Download className="h-4 w-4" /></button></div>)}</div><button type="button" onClick={signOut} className="mt-4 flex items-center gap-2 text-xs font-semibold text-ink-muted hover:text-crimson"><LogOut className="h-3.5 w-3.5" /> Sign out</button></aside>;
}
